[calibration]
enabled = true
last_total_calibration_date = "2024-01-01T00:00:00Z"
[calibration.parameters]
[[calibration.parameters.camera]]
last_calibration_date = "2024-01-01T00:00:00Z"
exposure = 100
gain = 1.0
white_balance = "auto"
focus = "auto"
intrinsic_matrix = [1000.0, 0.0, 960.0, 0.0, 1000.0, 540.0, 0.0, 0.0, 1.0]
distortion_coefficients = [0.1, -0.05, 0.0, 0.0, 0.0]
[[calibration.parameters.camera]]
last_calibration_date = "2024-01-01T00:00:00Z"
exposure = 100
gain = 1.0
white_balance = "auto"
focus = "auto"
intrinsic_matrix = [1000.0, 0.0, 960.0, 0.0, 1000.0, 540.0, 0.0, 0.0, 1.0]
distortion_coefficients = [0.1, -0.05, 0.0, 0.0, 0.0]
[[calibration.parameters.microphone]]
last_calibration_date = "2024-01-01T00:00:00Z"
sensitivity = 1.0
noise_reduction = true
[[calibration.parameters.microphone]]
last_calibration_date = "2024-01-01T00:00:00Z"
sensitivity = 1.0
noise_reduction = true
