#pragma once

#include <string>

namespace sst::network {

// An autonomous WiFi Direct P2P group, as actually formed by wpa_supplicant
// (KTD4). The SSID/passphrase are GENERATED by the group owner, not pre-shared
// — the camera reads them back and reports them to the app over BLE so the app
// joins whatever the camera created.
struct WifiDirectGroup {
    std::string ssid;
    std::string psk;
    std::string group_interface;  // e.g. "p2p-wlan0-0"
    std::string group_owner_ip;   // static GO IP, e.g. "192.168.49.1"
    std::string role;             // "GO"
};

}  // namespace sst::network
