#pragma once

#include <cstdint>
#include <optional>
#include <string>

namespace sst::config {

// WiFi-Direct (Group Owner) bring-up settings. Read straight from
// /etc/sst/cam/config/wifi-direct.json (KTD8) — config files are the only
// persistent state after the app-as-source-of-truth refactor. For an autonomous
// P2P group owner (U12) the SSID/passphrase are generated by wpa_supplicant at
// group-add time and reported back over BLE; these fields are fallback/defaults.
struct WifiDirectData {
    std::optional<bool> enabled{std::nullopt};
    std::optional<std::string> ssid{std::nullopt};
    std::optional<std::string> passphrase{std::nullopt};
    std::optional<std::uint32_t> channel{std::nullopt};
    std::optional<std::string> ip_address{std::nullopt};
};

}  // namespace sst::config
