name: sst-cam-firmware

services:
  sst-cam-firmware-builder:
    container_name: sst-cam-firmware-builder
    image: sst-cam-firmware-builder:jetpack_6.2.2-l4t_36.5.0
    build:
      context: ..
      dockerfile: docker/Dockerfile.cross
      args:
        - SW_VERSION=6.1
    working_dir: /workspace
    volumes:
      - ..:/workspace
      - ../.cache:/.cache
    environment:
      - CONAN_HOME=/home/builder/.conan2
    command: bash -lc "./scripts/bootstrap-cross-compiling.sh && exec bash"
